// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIRvgfM77mB2e1RA_OyH7IPiVoqm4J_R8',
    appId: '1:970695514671:android:5e54cf8485adefef10c4da',
    messagingSenderId: '970695514671',
    projectId: 'chronolift-66ed4',
    storageBucket: 'chronolift-66ed4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT_4IhjEkytETsUmWv2sTjSv0ZaYvmW58',
    appId: '1:970695514671:ios:b573b2332e585d6510c4da',
    messagingSenderId: '970695514671',
    projectId: 'chronolift-66ed4',
    storageBucket: 'chronolift-66ed4.firebasestorage.app',
    iosBundleId: 'com.example.chronolift',
  );
}