name: Flutter iOS/Android Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.8
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      # - name: Build Android
      #   run: flutter build apk --debug

      - name: Build iOS
        run: flutter build ios --no-codesign